runtime: python311

# Instance configuration
instance_class: F2

# Scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Environment variables
env_variables:
  PORT: 8080
  PYTHONPATH: /app

# Resource limits
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Health check
liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300 