steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/power-ai:$BUILD_ID', '.']
  
  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/power-ai:$BUILD_ID']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'power-ai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/power-ai:$BUILD_ID'
      - '--region'
      - 'europe-west9'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--port'
      - '8080'

# Store the Docker image in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/power-ai:$BUILD_ID'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

# Timeout for the entire build
timeout: '1200s' 